### PR TITLE
filter out null before replacing module source

### LINKED ISSUE #92: SvgStorePlugin fails if there are any other unrelated errors in the build
Hey! I've run into an issue when there's some sort of error in my build (for example, an eslint error that comes via eslint-loader), then SvgStorePlugin fails. That's probably because webpack does not emit if there are any errors.

Versions (ask if anything else may be of importance):
```
"webpack": "^5.16.0"
"external-svg-sprite-loader": "^7.1.1"
```

Stack trace:
```
/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:223
                    if (typeof source._name === 'string') {
                                      ^

TypeError: Cannot read property '_name' of null
    at SvgStorePlugin.replaceSpritePathsInModuleWithInterpolatedPaths (/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:223:39)
    at SvgStorePlugin.fixSpritePathsInModules (/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:97:22)
    at Hook.eval [as call] (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at Hook.CALL_DELEGATE [as _call] (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compilation.js:2096:37)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compiler.js:1054:20
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compilation.js:1925:4
    at _next4 (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:332:11
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:311:18
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:46:16
```

### PR DESCRIPTION
**Pull request by mihkeleidast**
Fixes #92.

### CODE REVIEW

**Comment by schinery** [comment]
@mihkeleidast looks like this is blocked from being merged as you need to have signed GitHub commits setup. 

Do you wanna want to do that and recreate this PR with a signed commit?

**Comment by mihkeleidast** [comment]
Uhh I have no idea currently how to make that work. Is that the only thing blocking the merge/release of this? Because, by all means, this oneliner fix does not need to be merged by this commit, it can be committed directly if someone has permissions.

**Comment by schinery** [comment]
TBH am not sure, I stumbled upon this PR from issue #92 you raised as I had the same thing. I tried your fix locally and it worked for me so I was trying to see if this got get added. 

@bensampaio would you be able to add this to an upcoming version?

**Comment by schinery** [comment]
FYI @mihkeleidast you can find out how to set up verified GitHub commits [here](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification#gpg-commit-signature-verification) 👍🏻

**Comment by mihkeleidast** [comment]
Yeah, I know about that guide. I tried it once and failed, probably because I'm coding in WSL2 but using [Fork](https://git-fork.com/) as my Git GUI. Those two use different git executables (I think) and sharing stuff like keys is a hassle.

**Comment by mihkeleidast** [comment]
Closing since it's a dupe of already merged #96.

**Pull request closed without merging**
